### PR TITLE
Fix typo's, add Remix

### PR DESCRIPTION
**Pull request by pclaesen**

### CODE REVIEW

**Comment by tesla809** [comment]
Thanks for PR! Could you pull, get new updates and resolve conflict?
Basically, I moved around the directory structure.

**Comment by tesla809** [comment]
Hey hey, would love to merge! Can you pull in the new repo, and solve the merge conflicts?

**Comment by pclaesen** [comment]
Should be good now I think?

**Comment by tesla809** [comment]
Woohoo! LGTM! The first Pull Request! Congrats @pclaesen!

**Comment by tesla809** [comment]
Umm, the deployment seems to be using some old code? I am still not a Vercel pro, but have you pulled from the latest main branch, then made the commits? The design and assets in your deployment seem different.

**Pull request closed without merging**
